### ISSUE TITLE
RomeAdapter uses deprecated HTTPClient APIs that prevent it from establishing some SSL connections

### ISSUE THREAD

**Issue by drewwills** [uPortal-Project/NewsReaderPortlet#72]
Here is an issue ticket from the Eureka project that seems to capture our situation well...

  - https://github.com/Netflix/eureka/issues/873

Here is the place in the Spring context where we create the `httpClient` bean...

  - https://github.com/Jasig/NewsReaderPortlet/blob/master/src/main/resources/context/applicationContext.xml#L87

`DefaultHttpClient` is deprecated;  we're meant to use `HttpClientBuilder`.

**Comment by bjagg** [comment]
Some useful links:

- https://www.chronicle.com/section/News/6/rss (another example feed)
- https://stackoverflow.com/questions/39762760/javax-net-ssl-sslexception-certificate-doesnt-match-any-of-the-subject-alterna
- https://github.com/rest-assured/rest-assured/issues/497
- https://www.springbyexample.org/examples/contact-rest-services-client.html
- https://hc.apache.org/httpcomponents-client-4.5.x/httpclient/apidocs/org/apache/http/impl/client/DecompressingHttpClient.html
- https://hc.apache.org/httpcomponents-client-4.5.x/tutorial/html/connmgmt.html
- https://stackoverflow.com/questions/20340470/how-to-spring-ioc-and-httpclient-4-3-1-closeablehttpclient
